client_id: qwtMsHAh1Wtd17E8mnho2Nhg7XYezGoL6qdPdtpN
client_secret: NBkUo3Zh5t4iBustDNYudbibwPsOXbxL8fyG97ZzSX1KqYFv4gvDVVMXI73AF6PVUd0ia3abOm7D4y4IMoJMZqvLcI8rC51JZqf8jA1tAd2LStWiUL31w9axfPszLtDL

base_urls:
    lms: https://dev.courses.multisitesdev.edly.io
    ecommerce: ECOM_BASE_URL
    credentials: CREDS_BASE_URL

retirement_pipeline:
    - ['RETIRING_ENROLLMENTS', 'ENROLLMENTS_COMPLETE', 'LMS', 'retirement_unenroll']
    - ['RETIRING_LMS', 'LMS_COMPLETE', 'LMS', 'retirement_lms_retire']
    - ['RETIRING_LMS_MISC', 'LMS_MISC_COMPLETE', 'LMS', 'retirement_lms_retire_misc']
    - ['RETIRING_FORUM', 'FORUM_COMPLETE', 'LMS', 'retirement_retire_forum']
    - ['RETIRING_PROCTORING', 'PROCTORING_COMPLETE', 'LMS', 'retirement_retire_proctoring_data']

